apiVersion: covetrol/v1
kind: Pod
metadata:
    name: busybox-pod
spec:
    containers:
        - name: main
          image: busybox
          command:
              - /bin/busybox
              - sleep
          args:
              - '600'
