apiVersion: covetrol/v1
kind: ReplicaSet
metadata:
    name: busybox-rs
spec:
  replicas: 1
  selector:
    app: busybox
    rs: busybox-rs
  template:
    apiVersion: covetrol/v1
    kind: Pod
    metadata:
      name: busybox
      labels:
        app: busybox
        rs: busybox-rs
    spec:
      containers:
                - name: main
                  image: busybox
                  command:
                      - /bin/busybox
                      - sleep
                  args:
                      - '600'
